---
driver:
  name: vagrant
  customize:
    memory: '1024'

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.6
  - name: debian-8.1
    run_list:
    - recipe[apt]

suites:
  - name: default
    run_list:
    - recipe[build-essential]
    - recipe[minitest-handler]
    - recipe[backup_test::default]
  - name: chef10
    run_list:
    - recipe[build-essential]
    - recipe[minitest-handler]
    - recipe[backup_test::default]
    provisioner:
      require_chef_omnibus: 10.30.2
  - name: disable
    run_list:
    - recipe[build-essential]
    - recipe[minitest-handler]
    - recipe[backup_test::disable]
  - name: remove
    run_list:
    - recipe[build-essential]
    - recipe[minitest-handler]
    - recipe[backup_test::remove]
